### ISSUE TITLE
Cannot find module '../lib/cli'

### ISSUE THREAD

**Issue by kowalcj0** [Naturalclar/klank#43]
Hi @Naturalclar 

I just tried to use the `v0.1.2` but it looks like somehow `lib/cli` folder is not being packaged, and thus it creates a problem.

Initially I tried to install it globally:
```shell
$ npm install -g moxci
/home/user/.npm_modules/bin/moxci -> /home/user/.npm_modules/lib/node_modules/moxci/bin/run
+ moxci@0.1.2
added 74 packages from 81 contributors in 3.161s
```

When I run it using `npx` I'm getting only a short error message:
```shell
$ npx moxci --help
Cannot find module '../lib/cli'
Require stack:
- /home/user/.npm_modules/lib/node_modules/moxci/bin/run
```

When I call it directly a whole stack trace is being printed out:
```node
$ moxci --help
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '../lib/cli'
Require stack:
- /home/user/.npm_modules/lib/node_modules/moxci/bin/run
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/.npm_modules/lib/node_modules/moxci/bin/run:2:14)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/user/.npm_modules/lib/node_modules/moxci/bin/run' ]
}
```

Same thing happens when I install it in a project:
```shell
$ npm i moxci

+ moxci@0.1.2
added 74 packages from 81 contributors and audited 162 packages in 3.298s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


$ ./node_modules/.bin/moxci --help
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '../lib/cli'
Require stack:
- /home/user/git/dit/directory-tests/node_modules/moxci/bin/run
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/git/dit/directory-tests/node_modules/moxci/bin/run:2:14)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/user/git/dit/directory-tests/node_modules/moxci/bin/run' ]
}
```

Not sure what made `yarn build` to ignore `lib/cli` directory. :(

PS. when I build the project locally with `yarn build`, then all is fine:
```
$ yarn build
yarn run v1.21.1
$ tsc
Done in 3.34s.

$ tree lib
lib
├── cli
│   ├── index.js
│   └── options.js
├── get-artifact.js
├── github-notify.js
├── index.js
├── index.test.js
└── slack-notify.js

1 directory, 7 files
```

**Comment by kowalcj0** [comment]
Maybe we should add `"lib/cli"` to `package.json`:
```json
  "files": [
    "bin",
    "lib",
    "lib/cli",
    "package.json",
    "README.md"
  ],
```
or use a glob pattern `"lib/**/*"` as described in https://docs.npmjs.com/files/package.json#files ?

**Comment by Naturalclar** [comment]
Hey @kowalcj0 , sorry for causing you trouble 😢 
I've just published 0.1.3 and it should be working now.
Not too sure what went wrong..
when I published 0.1.2, I didn't build the files locally before publishing, but that shouldn't have been a problem as I have `publish` script that automatically runs `yarn build` before publishing 🤔

**Comment by kowalcj0** [comment]
Great!
Thank you for your help. Will install it now :)

**Comment by Naturalclar** [comment]
@kowalcj0 has this worked out for you?
If so, I can close the issue 😃

**Comment by kowalcj0** [comment]
It worked like a charm.
Thanks @Naturalclar 

I'm really happy with the custom Slack notifications :) (and a bit less with broken tests ;)
![image](https://user-images.githubusercontent.com/910451/74422215-2d207300-4e46-11ea-94b2-349f85f765ec.png)
